CONFIG:
  你的邮箱:
    你的cloudflare api:
      你要修改的域名ID1:
        你要修改的域名解析记录ID1:
           CM:
            HKG
        你要修改的域名解析记录ID2:
           CU:
            SEA
        你要修改的域名解析记录ID3:
           CT:
            ALL
      你要修改的域名ID2: 
         #在此处添加，格式如上，注意缩进
MODE: 3