CONFIG:
  - your_email:
    api: your_cloudflare_api
    your_domain_id:
      your_dns_id:
           CM: HKG
      your_dns_id2:
           CU: SEA
      your_dns_id3:
           CT: ALL
    your_domain_id2: 
         #在此处添加，格式如上，注意缩进
MODE: 3